// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  explainer: dynamic(() => import("./Explainer")),
  hanna: dynamic(() => import("./HannaSlice")),
  hero: dynamic(() => import("./Hero")),
  mikias_slice: dynamic(() => import("./MikiasSlice")),
  sarthak: dynamic(() => import("./Sarthak")),
  testimonials: dynamic(() => import("./Testimonials")),
};
