// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  hanna: dynamic(() => import("./HannaSlice")),
  hero: dynamic(() => import("./Hero")),
  mikias_slice: dynamic(() => import("./MikiasSlice")),
  split_feature_block: dynamic(() => import("./SplitFeatureBlock")),
  team_cards_section: dynamic(() => import("./TeamCardsSection")),
  three_column_explainer: dynamic(() => import("./ThreeColumnExplainer")),
  sarthak: dynamic(() => import("./Sarthak")),
  theming: dynamic(() => import("./Theming")),
};
